-- ============================================================
-- ONTOLOGY SCHEMA MIGRATION — Phase 4
-- ============================================================
-- RUN THIS IN NEON CONSOLE FIRST — before deploying code changes.
--
-- Creates 4 ontology tables and seeds entity types + relationship types.
-- Safe to re-run (uses IF NOT EXISTS and ON CONFLICT DO NOTHING).
-- ============================================================

-- Table 1: Entity Types (taxonomy classes from Section 2)
CREATE TABLE IF NOT EXISTS ontology_entity_types (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  parent_type_id INTEGER REFERENCES ontology_entity_types(id) ON DELETE SET NULL,
  definition TEXT,
  attributes_schema JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 2: Entities (instances — companies, certifications, technologies, etc.)
CREATE TABLE IF NOT EXISTS ontology_entities (
  id SERIAL PRIMARY KEY,
  type_id INTEGER NOT NULL REFERENCES ontology_entity_types(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  aliases TEXT[] DEFAULT '{}',
  attributes JSONB DEFAULT '{}',
  prospect_company_id INTEGER REFERENCES prospect_companies(id) ON DELETE SET NULL,
  source VARCHAR(255),
  confidence VARCHAR(20) DEFAULT 'Confirmed',
  layer INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(type_id, name)
);

-- Table 3: Relationship Types (verbs from Section 3)
CREATE TABLE IF NOT EXISTS ontology_relationship_types (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  domain_type_id INTEGER REFERENCES ontology_entity_types(id),
  range_type_id INTEGER REFERENCES ontology_entity_types(id),
  definition TEXT,
  inverse_name VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 4: Relationships (edges — the actual triples)
CREATE TABLE IF NOT EXISTS ontology_relationships (
  id SERIAL PRIMARY KEY,
  type_id INTEGER NOT NULL REFERENCES ontology_relationship_types(id) ON DELETE RESTRICT,
  subject_entity_id INTEGER NOT NULL REFERENCES ontology_entities(id) ON DELETE CASCADE,
  object_entity_id INTEGER NOT NULL REFERENCES ontology_entities(id) ON DELETE CASCADE,
  source VARCHAR(255),
  confidence VARCHAR(20) DEFAULT 'Confirmed',
  effective_date DATE,
  end_date DATE,
  layer INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(type_id, subject_entity_id, object_entity_id)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_ontology_entities_type ON ontology_entities(type_id);
CREATE INDEX IF NOT EXISTS idx_ontology_entities_prospect ON ontology_entities(prospect_company_id) WHERE prospect_company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ontology_entities_layer ON ontology_entities(layer);
CREATE INDEX IF NOT EXISTS idx_ontology_relationships_subject ON ontology_relationships(subject_entity_id);
CREATE INDEX IF NOT EXISTS idx_ontology_relationships_object ON ontology_relationships(object_entity_id);
CREATE INDEX IF NOT EXISTS idx_ontology_relationships_type ON ontology_relationships(type_id);
CREATE INDEX IF NOT EXISTS idx_ontology_relationships_layer ON ontology_relationships(layer);

-- ============================================================
-- SEED: Entity Types (Section 2 of ontology doc)
-- ============================================================
INSERT INTO ontology_entity_types (name, definition) VALUES
  ('Company', 'An organization that manufactures plastic parts, builds molds/tooling, or provides technology/services to the plastics manufacturing industry'),
  ('Manufacturing Process', 'A method by which raw plastic material is transformed into a finished or semi-finished part'),
  ('Equipment Brand', 'A manufacturer of physical machinery, instrumentation, or automation hardware used in plastics manufacturing'),
  ('Technology / Software', 'A software platform, monitoring system, simulation tool, or digital capability used in plastics manufacturing'),
  ('Material', 'A raw plastic resin, compound, or additive processed by a converter or specified in mold design'),
  ('Certification', 'A formal accreditation, registration, or quality management system standard held by a company'),
  ('Market Vertical', 'An end-market industry sector served by a plastics manufacturer'),
  ('Quality Method', 'A systematic methodology, technique, or practice used to control, monitor, or improve manufacturing quality'),
  ('Ownership Structure', 'The governance and capital structure of a manufacturing company'),
  ('Workforce Capability', 'A documented skill, credential, or training program indicating technical sophistication'),
  ('Data Type', 'A category of data generated by plastics manufacturing operations with potential AI/ML value'),
  ('Readiness Signal', 'An observable indicator that a company is likely to benefit from alliance engagement')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- SEED: Relationship Types (Section 3 of ontology doc)
-- ============================================================

-- Company → Process/Technology/Certification relationships
INSERT INTO ontology_relationship_types (name, domain_type_id, range_type_id, definition, inverse_name) VALUES
  ('operates_process',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Manufacturing Process'),
    'Company performs this manufacturing process', 'is_operated_by'),
  ('uses_technology',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    'Company has this technology deployed in operations', 'is_used_by'),
  ('uses_equipment_brand',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Equipment Brand'),
    'Company operates machines from this manufacturer', 'equips'),
  ('holds_certification',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Certification'),
    'Company maintains this active certification', 'is_held_by'),
  ('serves_market',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Market Vertical'),
    'Company produces parts for this end-market', 'is_served_by'),
  ('employs_method',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Quality Method'),
    'Company practices this quality methodology', 'is_employed_by'),
  ('processes_material',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Material'),
    'Company molds or extrudes this material type', 'is_processed_by'),
  ('generates_data',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Data Type'),
    'Company operations produce this category of data', 'is_generated_by'),
  ('has_workforce_capability',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Workforce Capability'),
    'Company employees hold this credential or skill', NULL),
  ('has_ownership_structure',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Ownership Structure'),
    'Company is governed by this ownership type', NULL),
  ('has_readiness_signal',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Readiness Signal'),
    'Company exhibits this engagement indicator', NULL)
ON CONFLICT (name) DO NOTHING;

-- Company → Company relationships
INSERT INTO ontology_relationship_types (name, domain_type_id, range_type_id, definition, inverse_name) VALUES
  ('subsidiary_of',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject is a subsidiary or division of object', 'parent_of'),
  ('acquired_by',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject was purchased by object', 'acquired'),
  ('parent_of',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject is the parent or holding company of object', 'subsidiary_of'),
  ('partners_with',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Formal partnership or strategic relationship', 'partners_with'),
  ('competes_with',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject and object compete in the same market space', 'competes_with'),
  ('supplies_to',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject provides products or services to object', 'is_supplied_by'),
  ('sister_company_of',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Both share the same parent company', 'sister_company_of'),
  ('legacy_name_of',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject is a former name for what is now the object', 'currently_known_as'),
  ('absorbed_into',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    'Subject was absorbed or consolidated into object', 'absorbed')
ON CONFLICT (name) DO NOTHING;

-- Technology / Process / Certification cross-relationships
INSERT INTO ontology_relationship_types (name, domain_type_id, range_type_id, definition, inverse_name) VALUES
  ('monitors',
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Manufacturing Process'),
    'Technology monitors or controls this process', NULL),
  ('requires_certification',
    (SELECT id FROM ontology_entity_types WHERE name = 'Market Vertical'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Certification'),
    'This market typically requires this certification', NULL),
  ('produces_data',
    (SELECT id FROM ontology_entity_types WHERE name = 'Manufacturing Process'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Data Type'),
    'This process generates this type of data', 'is_generated_by'),
  ('enables_method',
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Quality Method'),
    'This technology enables or supports this quality method', NULL),
  ('manufactures',
    (SELECT id FROM ontology_entity_types WHERE name = 'Company'),
    NULL,
    'This company makes or sells this product', NULL),
  ('successor_of',
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    'This technology replaced or evolved from the earlier one', NULL),
  ('integrates_with',
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    'These technologies have documented data integration', NULL),
  ('embedded_in',
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    (SELECT id FROM ontology_entity_types WHERE name = 'Technology / Software'),
    'This technology is natively included in another', NULL)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- VERIFICATION: Run these after migration to confirm success
-- ============================================================
-- SELECT COUNT(*) AS entity_type_count FROM ontology_entity_types;  -- Expected: 12
-- SELECT COUNT(*) AS relationship_type_count FROM ontology_relationship_types;  -- Expected: 23
-- SELECT name FROM ontology_entity_types ORDER BY id;
-- SELECT name FROM ontology_relationship_types ORDER BY id;
